/* --------------------------------------------------------------------------------------------------------------------------------- */
/* C8 Parte 1 */

/* Realizar el análisis univariado de la variable MONTO_SOLICITADO y guardar en la base de datos ORIGINA con el nombre 
UNIV_MONTO_SOLICITADO */

PROC SQL;
CREATE TABLE WORK.TEMPORAL AS
SELECT 		S.CLIENTE,
			MONTO_SOLICITADO as MONTO_SOLICITADO_ORIGINAL,
			CASE 
				WHEN	MONTO_SOLICITADO IS NULL THEN .
				ELSE 	MONTO_SOLICITADO
			END AS MONTO_SOLICITADO,
			F.BAD
FROM		ORIGINA.SOLICITUD 		AS S
INNER JOIN	ORIGINA.FLAG_G_B 		AS F ON F.CLIENTE=S.CLIENTE
INNER JOIN  ORIGINA.DEMOGRAFICOS 	AS D ON D.CLIENTE=S.CLIENTE
INNER JOIN  ORIGINA.BURO 			AS B ON B.CLIENTE=S.CLIENTE;
QUIT;

PROC UNIVARIATE DATA=WORK.TEMPORAL NOPRINT;			/* Generar rangos con al menos el 5% de la población cada uno de ellos */
VAR MONTO_SOLICITADO;
OUTPUT OUT=WORK.RANGOS PCTLPRE=P_ PCTLPTS=0 TO 100 BY 5;		
RUN;

PROC SQL;
CREATE TABLE WORK.RA_SQL_MONTO_SOLICITADO AS 
SELECT 	RANGO_MONTO_SOLICITADO,
		COUNT(CLIENTE) AS CLIENTES,
		SUM(BAD) AS BADS,
		AVG(BAD) AS PORCENTAJE_BADS
FROM
(   	/**************************************** Z ****************************************/
	SELECT 	CLIENTE,
			BAD,
			MONTO_SOLICITADO,
			CASE 
			WHEN MONTO_SOLICITADO >= 1500  AND MONTO_SOLICITADO < 3000  THEN '00 1500 - 3000'
			WHEN MONTO_SOLICITADO >= 3000  AND MONTO_SOLICITADO < 5000  THEN '01 3000 - 5000'
			WHEN MONTO_SOLICITADO >= 5000  AND MONTO_SOLICITADO < 6000  THEN '02 5000 - 6000'
			WHEN MONTO_SOLICITADO >= 6000  AND MONTO_SOLICITADO < 7000  THEN '03 6000 - 7000'
			WHEN MONTO_SOLICITADO >= 7000  AND MONTO_SOLICITADO < 8000  THEN '04 7000 - 8000'
			WHEN MONTO_SOLICITADO >= 8000  AND MONTO_SOLICITADO < 9000  THEN '05 8000 - 9000'
			WHEN MONTO_SOLICITADO >= 9000  AND MONTO_SOLICITADO < 10000 THEN '06 9000 - 10000'
			WHEN MONTO_SOLICITADO >= 10000 AND MONTO_SOLICITADO < 15000 THEN '07 10000 - 15000'
			WHEN MONTO_SOLICITADO >= 15000 AND MONTO_SOLICITADO < 20000 THEN '08 15000 - 20000'
			WHEN MONTO_SOLICITADO >= 20000 								THEN '09 20000 - MAS'
			END AS RANGO_MONTO_SOLICITADO
		FROM	WORK.TEMPORAL
) AS Z	/**************************************** Z ****************************************/
GROUP BY 1
ORDER BY 1
;QUIT;


/**************************************** UNIVARIADO_MONTO_SOLICITADO ****************************************/
PROC SQL;
CREATE TABLE ORIGINA.UNIV_MONTO_SOLICITADO AS 
SELECT 	RANGO_MONTO_SOLICITADO,
		COUNT(CLIENTE) AS CLIENTES,
		SUM(BAD) AS BADS,
		AVG(BAD) AS PORCENTAJE_BADS
FROM
(   	/**************************************** Z ****************************************/
	SELECT 	CLIENTE,
			BAD,
			MONTO_SOLICITADO,
			CASE 
			WHEN MONTO_SOLICITADO >= 1500  AND MONTO_SOLICITADO < 3000  THEN '00 1500 - 3000'
			WHEN MONTO_SOLICITADO >= 3000  AND MONTO_SOLICITADO < 5000  THEN '01 3000 - 5000'			
			WHEN MONTO_SOLICITADO >= 5000  AND MONTO_SOLICITADO < 8000  THEN '02 5000 - 8000'
			WHEN MONTO_SOLICITADO >= 8000     							THEN '03 8000 - MAS'
			END AS RANGO_MONTO_SOLICITADO
		FROM	WORK.TEMPORAL
) AS Z	/**************************************** Z ****************************************/
GROUP BY 1
ORDER BY 1
;QUIT;




/* --------------------------------------------------------------------------------------------------------------------------------- */
/* C8 Parte 2 */









