/* 13 FEBRERO 2025 */

/* EJERCICIO VIDEO C4 */
/*Crear un par de tablas de nombre E9SQL y E9SAS que contengan los siguientes campos:
Cliente, Nombre, Apellido Paterno, Fecha de Nacimiento, Fecha en que se hizo la solicitud,
Edad, Ingreso Total. Aplicando los siguienes filtros: Ingreso Total > 10000 y Edad > 24*/

/*SQL*/
PROC SQL;
CREATE TABLE WORK.E9SQL AS
SELECT 	N.CLIENTE, 
		N.NOMBRE_SOLIC,
		N.APPATERNO_SOLIC,
		D.FECHA_NACIMIENTO,
		S.FECHA_SOLICITUD,
		INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD) AS EDAD,
		INGRESO_FIJO + INGRESO_VARIABLE AS INGRESO_TOTAL
FROM ORIGINA.NOMBRE AS N 
LEFT JOIN ORIGINA.DEMOGRAFICOS AS D ON N.CLIENTE = D.CLIENTE
LEFT JOIN ORIGINA.SOLICITUD AS S ON S.CLIENTE = N.CLIENTE
WHERE D.INGRESO_FIJO + INGRESO_VARIABLE > 10000 
  AND INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD) > 24;   
QUIT;

/*SAS*/
DATA WORK.E9SAS;
MERGE 	ORIGINA.NOMBRE (IN=N) 
		ORIGINA.DEMOGRAFICOS (IN=D)
		ORIGINA.SOLICITUD (IN=S);
		INGRESO_TOTAL = INGRESO_FIJO + INGRESO_VARIABLE;
		EDAD = INTCK('YEAR',FECHA_NACIMIENTO,FECHA_SOLICITUD);
BY 		CLIENTE;
KEEP CLIENTE NOMBRE_SOLIC APPATERNO_SOLIC FECHA_NACIMIENTO FECHA_SOLICITUD EDAD INGRESO_TOTAL;
IF INGRESO_TOTAL > 10000;
IF EDAD > 24;
RUN;

/* MINI EXAMEN */
/* Crear un par de tablas de nombre E10SQL y E10SAS que contengan los siguientes campos:
Cliente, Nombre, Apellido Paterno, Monto Solicitado, Ingreso Total, Edad, Estatus y BC Score.
Aplicar los siguientes filtros: Ingreso Total > 10000, Mas de 40 años de edad, Vivir en el DF, Solo clientes
aprobados (ie estatus = "A") y BC Score > 650 */

/* SQL */
PROC SQL;
CREATE TABLE WORK.E10SQL AS
SELECT 	  	N.CLIENTE,
		  	N.NOMBRE_SOLIC,
		  	N.APPATERNO_SOLIC,
		  	S.MONTO_SOLICITADO,
		  	D.INGRESO_FIJO + D.INGRESO_VARIABLE AS INGRESO_TOTAL,
		  	INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD) AS EDAD,
		  	A.ESTATUS,
		  	BURO.BC_SCORE
FROM 	  	ORIGINA.NOMBRE AS N 
LEFT JOIN 	ORIGINA.DEMOGRAFICOS AS D ON N.CLIENTE = D.CLIENTE
LEFT JOIN 	ORIGINA.SOLICITUD AS S ON S.CLIENTE = N.CLIENTE
LEFT JOIN 	ORIGINA.BURO AS B ON B.CLIENTE = N.CLIENTE
LEFT JOIN 	ORIGINA.APROBADAS AS A ON A.CLIENTE = N.CLIENTE
WHERE     	D.INGRESO_FIJO + D.INGRESO_VARIABLE > 10000
AND   		INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD)>40
AND			D.ESTADO = "DISTRITO FEDERAL"
AND 		A.ESTATUS = "A"
AND 		B.BC_SCORE > 650;
QUIT;

/* SAS */
DATA WORK.E10SAS;
MERGE		ORIGINA.NOMBRE (IN=N)
			ORIGINA.DEMOGRAFICOS (IN=D)
			ORIGINA.SOLICITUD (IN=S)
			ORIGINA.BURO (IN=B)
			ORIGINA.APROBADAS (IN=A);
			INGRESO_TOTAL = INGRESO_FIJO + INGRESO_VARIABLE;
			EDAD = INTCK('YEAR',FECHA_NACIMIENTO,FECHA_SOLICITUD);
BY			CLIENTE;
IF 			INGRESO_TOTAL > 10000;
IF			EDAD > 40;
IF			ESTADO = "DISTRITO FEDERAL";
IF          ESTATUS = "A";
IF			BC_SCORE > 650;
RUN;


/*EJERCICIO 4 TAREA 1*/
/* Crear una tabla T7SQL y T8SAS dentro de la base de datos WORK que contenga los 
siguientes campos: Cliente, apellido paterno, apellido materno, Nombres, Estado, Sexo, 
Fecha de nacimiento, Ingreso total, Edad, Estatus (de si fue aprobado o rechazado su 
crédito), BC Score, Monto Solicitado. Aplicando los siguientes filtros: estatus aprobado, 
ingreso total >= 10mil pesos, BC Score > 0 , que vivan en el distrito Federal y que tengan 
más de 24 años.  */

/* SQL */
PROC SQL;
CREATE TABLE WORK.T7SQL AS
SELECT      N.CLIENTE,
			N.APPATERNO_SOLIC,
			N.APMATERNO_SOLIC,
			N.NOMBRE_SOLIC,
			D.ESTADO,
			D.SEXO,
			D.FECHA_NACIMIENTO,
			D.INGRESO_FIJO + D.INGRESO_VARIABLE AS INGRESO_TOTAL,
			INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD) AS EDAD,
			A.ESTATUS,
			BURO.BC_SCORE,
			S.MONTO_SOLICITADO
FROM 	  	ORIGINA.NOMBRE AS N 
LEFT JOIN 	ORIGINA.DEMOGRAFICOS AS D ON N.CLIENTE = D.CLIENTE
LEFT JOIN 	ORIGINA.SOLICITUD AS S ON S.CLIENTE = N.CLIENTE
LEFT JOIN 	ORIGINA.BURO AS B ON B.CLIENTE = N.CLIENTE
LEFT JOIN 	ORIGINA.APROBADAS AS A ON A.CLIENTE = N.CLIENTE
WHERE		A.ESTATUS = "A"
AND			D.INGRESO_FIJO + D.INGRESO_VARIABLE > 10000
AND         B.BC_SCORE > 0
AND         D.ESTADO = "DISTRITO FEDERAL"
AND         INTCK('YEAR',D.FECHA_NACIMIENTO,S.FECHA_SOLICITUD) > 24;
QUIT;

/* SAS */
DATA WORK.T8SAS;
MERGE		ORIGINA.NOMBRE (IN=N)
			ORIGINA.DEMOGRAFICOS (IN=D)
			ORIGINA.SOLICITUD (IN=S)
			ORIGINA.BURO (IN=B)
			ORIGINA.APROBADAS (IN=A);
			INGRESO_TOTAL = INGRESO_FIJO + INGRESO_VARIABLE;
			EDAD = INTCK('YEAR',FECHA_NACIMIENTO,FECHA_SOLICITUD);
BY          CLIENTE;
IF          ESTATUS = "A";
IF 			INGRESO_TOTAL > 10000;
IF			BC_SCORE > 0;
IF			ESTADO = "DISTRITO FEDERAL";
IF			EDAD > 24;
RUN;












